version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache-docker
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - rabbitmq
        volumes:
            - .:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq-local'
      ports:
          - 5672:5672
          - 15672:15672
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:15672"]
          interval: 30s
          timeout: 10s
          retries: 5
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

networks:
  rabbitmq_net:
    driver: bridge

